### ISSUE TITLE
FR: Show todo tasks in a simple, sorted, list

### ISSUE THREAD

**Issue by rasssta** [black-roland/homeassistant-microsoft-todo#43]
I only use Microsoft To-do's web interface to build plain and simple todo lists, and since I can't prioritise them (as I could in Wunderlist) in the tool I've named them according to "<1-5> - <task name".

I would like to be able to show this in a simple card in HASS to show what's the most important task(s) to start with in a project (I have multiple projects like this).

Is it possible to implement?

**Comment by black-roland** [comment]
Good question actually. I did a quick investigation and this should be pretty easy to do with the [Markdown card](https://www.home-assistant.io/lovelace/markdown/) since it supports Jinja templates. Just add a markdown card with the following content:

```yaml
type: markdown
content: |-
  {% for task in state_attr('calendar.PUT_YOUR_LIST_NAME_HERE', 'all_tasks') -%}
  - {{ task }}
  {% endfor %}
title: To Do
```

And as a result, you should get something like this:

![2021-02-03_01-55](https://user-images.githubusercontent.com/1756198/106674478-5a6cb080-65c4-11eb-9306-e363ff399f28.png)

If you would like to sort your tasks then you can use Jinja `sort` filter.

There should probably be some custom card component that can do the same better but unfortunately, I don't know of any. I've tried [iantrich/list-card](/iantrich/list-card) but it doesn't support plain string arrays (only object arrays).

I hope I answered your question.
