### ISSUE TITLE
Change time of sync

### ISSUE THREAD

**Issue by umutcelebi** [black-roland/homeassistant-microsoft-todo#65]
Is it possible to change the time of syncing between the cloud?
Since now it is only syncing when my HA instance restarts.

**Comment by black-roland** [comment]
Hmm, this is weird.

Could you please check if there are no related errors in the logs? You can find logs under Configuration > Logs (or by URL `http://<home_assistant_host>/config/logs`).

It would also be great if you could enable debug logs additionally. To do this, please update the [logger configuration](https://www.home-assistant.io/integrations/logger/):

```
logger:
  default: info
  logs:
    custom_components.microsoft_todo.calendar: debug
```

Normally you should see requests to load tasks from the cloud every 15 minutes.

Thanks.
