### ISSUE TITLE
Deprecation of homeassistant-microsoft-todo

### ISSUE THREAD

**Issue by black-roland** [black-roland/homeassistant-microsoft-todo#98]
Unfortunately, I didn't have much time resources to maintain this project so it's in a kind of abandoned state.

Home Assistant [2023.11](https://www.home-assistant.io/blog/2023/11/01/release-202311/) introduced new `todo` domain. I started looking into details and found out that there is a better alternative to my integration which already supports this new domain — [O365-HomeAssistant](https://github.com/RogerSelwyn/O365-HomeAssistant). It's maintained, well documented and has some extra features so probably there is not much sense in homeassistant-microsoft-todo integration anymore.

Please let me know if for some reason you'd like me to continue working on this project. Otherwise, I'd suggest migrating to O365-HomeAssistant.

**Comment by black-roland** [comment]
Migrating to O365-HomeAssistant should be relatively easy. You'd need to replace `microsoft_todo` configuration to something like this:

```
o365:
  accounts:
    - account_name: YourName
      client_id: "<the_same_id_as_for_microsoft_todo>"
      client_secret: "<the_same_secret_as_for_microsoft_todo>"
      alt_auth_method: False
      enable_update: False
      todo_sensors:
        enabled: True
        enable_update: True
```

Then in Azure you need to replace [redirect URI](https://rogerselwyn.github.io/O365-HomeAssistant/authentication.html) to `https://rogerselwyn.github.io/O365-HomeAssistant/authentication.html` and need to add [permissions for calendar and email](https://rogerselwyn.github.io/O365-HomeAssistant/permissions.html) if needed. You should get authorization request after restarting Home Assistant.

Also, please make sure to use [different syntax for adding new tasks](https://rogerselwyn.github.io/O365-HomeAssistant/services.html#task-services).
